### ISSUE TITLE
Implement combinator that makes IO action concurrent

### ISSUE THREAD

**Issue by ChShersh** [kowainik/co-log#10]
Like:

```haskell
runInOtherThread :: LogAction IO msg -> LogAction IO msg
```

**Comment by Cmdv** [comment]
I've done a little on concurrency with `Control.Parallel.Strategies` would this work for this issue, or did you have another in mind?
Also is it a case of trying to make all IO actions possible concurrent?

**Comment by qnikst** [comment]
I've implemented one approach in https://github.com/kowainik/co-log/pull/45 not sure if that is intended thing.

**Comment by ChShersh** [comment]
Fixed by @qnikst in #45
