### ISSUE TITLE
Add a function to log batch of messages independently

### ISSUE THREAD

**Issue by chshersh** [kowainik/co-log#122]
There is comonadic operator `multiplicate` that combines any number of messages into a single message and then logs singe message. It has the following implementation:

https://github.com/kowainik/co-log/blob/746016089a44e06dadf23818044285bd3ab22135/co-log-core/src/Colog/Core/Action.hs#L569-L574

It would be nice to have a function that can log any `Foldable` of messages by logging each message independently. This function has relation with the `Divisible` typeclass. 

```haskell
??? :: (Traversable f, Applicative m) => LogAction m msg -> LogAction m (f msg)
??? (LogAction action) = LogAction (traverse_ action)
```

**Unresolved question:** Name for the function.

On the other hand, it's just `contramap traverse_`....

**Comment by vrom911** [comment]
What about `separate` or `unjoin`, `separate`?

**Comment by chshersh** [comment]
@vrom911 I like `separate`, this sounds good :+1:
