### ISSUE TITLE
need example of rotation

### ISSUE THREAD

**Issue by pangwa** [kowainik/co-log#133]
below code doesn't rotate the log file at all, is there anything wrong?
```haskell
main = do
  withLogRotation (LimitTo 100) (LimitTo 10) "test.log" D.removeFile (
    \handle -> do
      encodeUtf8 . fmtMessage >$< (logByteStringHandle handle)) $ \action -> do
    runApp (AppEnv action) transApp

```

**Comment by chshersh** [comment]
@pangwa Support for logger rotation is experimental at the moment. It would be indeed nice to have a working example for it.

**Comment by chshersh** [comment]
I'm closing this issue since PR #135 is merged. An example will be added under issue with tutorial series.
