### ISSUE TITLE
Add Windows CI (AppVeyor)

### ISSUE THREAD

**Issue by chessai** [kowainik/co-log#144]
Chronos already built on Mac/Linux. Now, thanks to @nprindle and @ShrykeWindgrace, it builds (and works!) on Windows as well. This isn't anything for you to fix, I'm just notifying you of the good news. Thanks!

**Comment by chshersh** [comment]
@chessai Thanks for the notification! I think if `co-log` had Windows CI, such things could be noticed earlier and not leak into release. I'm renaming this issue to add Windows CI support for the future.

**Comment by ShrykeWindgrace** [comment]
On a side note, another solution would be to use Azure CI, which has a convenient option to run tests on all three major platforms, as opposed to Appveyor which only supports windows and linux.

**Comment by chshersh** [comment]
@ShrykeWindgrace Azure CI looks cool. But at this point, it doesn't support caching out-of-the-box. I don't have capacity at the moment to learn how to configure the cache manually with S3 buckets or something similar. However, I also heard that there is ongoing work on implementing caching on Azure CI. So once it's done, I will have a look at it. For now, we have standard AppVeyor CI config which can be copy-pasted without changes and configuring Windows CI is a 5-minute job.

**Comment by vrom911** [comment]
As a good reference point for AppVeryor CI configs: https://hub.zhox.com/posts/introducing-haskell-dev/

**Comment by chessai** [comment]
Awesome work guys. Thanks!
