### ISSUE TITLE
Question: JSON formatter

### ISSUE THREAD

**Issue by shinzui** [kowainik/co-log#157]
What's the best way to implement a JSON formatter?

**Comment by sshine** [comment]
In what way best? 

One way that is good in the sense that it's short, involves writing no code, and relies on [`aeson`](http://hackage.haskell.org/package/aeson), would be to simply use [`aeson-pretty`](http://hackage.haskell.org/package/aeson-pretty):

```
$ stack install aeson-pretty
$ echo "[1,2,3]" | aeson-pretty 
[
    1,
    2,
    3
]
$ echo -e "[1,2,3]" | aeson-pretty | aeson-pretty --compact
[1,2,3]
```

Used from within GHCi:

```
λ> import Data.Aeson.Encode.Pretty
λ> import Data.ByteString.Lazy as L
λ> L.putStrLn (encodePretty [1,2,3])
[
    1,
    2,
    3
]
λ> L.putStrLn (encodePretty' defConfig {confIndent = Spaces 0} [1,2,3])
[1,2,3]
```

Is your question rather about how to structure a module such as `aeson-pretty`?

**Comment by chshersh** [comment]
@shinzui I assume that you want to have a `LogAction` that prints any JSON value to stdout. So you want something like this:

```haskell
logJsonStdout :: (ToJSON msg, MonadIO m) => LogAction m msg
```

> where `ToJSON` is from the `aeson` library

You can build such action by using the fact that `LogAction` has `Contravariant` instance, so you can apply `contramap` here:

```haskell
logJsonStdout = contramap (ByteString.toStrict . Aeson.encode) logByteStringStdout
```

**Comment by shinzui** [comment]
I should have formulated my question better. I was looking for an efficient way to output structured logs to stdout so they can be ingested by fluentd. @chshersh answered my question, thank you.
