### ISSUE TITLE
add a natural transformation mapping over LogAction?

### ISSUE THREAD

**Issue by chessai** [kowainik/co-log#158]
```haskell
mapLogAction :: (forall x. m x -> n x) -> LogAction m msg -> LogAction n msg
mapLogAction eta (LogAction action) = LogAction (eta . action)
```

**Comment by vrom911** [comment]
We do have `hoistLogAction` function:

https://github.com/kowainik/co-log/blob/13f6c31d4eb9290c5a5c1ea8de0b2f9f8d0957fa/co-log-core/src/Colog/Core/Action.hs#L640-L645

**Comment by chessai** [comment]
okay, not a problem. didn't see that in the code, sorry.

thanks
