### ISSUE TITLE
New release for 8.8.1 and stackage nightlies

### ISSUE THREAD

**Issue by ejconlon** [kowainik/co-log#170]
I see support in master but not on hackage (co-log is still at 0.3, but master reflects the work in https://github.com/kowainik/co-log/issues/148). Are there any blockers for a release to get back in stackage nightlies? (Thank you for the great library!)

**Comment by chshersh** [comment]
@ejconlon There're no blockers. We organize our work and features in milestones and perform release only when all issues are done. We've been slowly working on a new milestone and it's almost done:

* https://github.com/kowainik/co-log/milestone/2

So you can expect a release on both Hackage and Stackage very soon :slightly_smiling_face:

**Comment by chshersh** [comment]
All `co-log` packages are in the latest Stackage nightly:

* https://www.stackage.org/nightly-2020-01-24
