### ISSUE TITLE
<unknown loc> with custom logException

### ISSUE THREAD

**Issue by mb720** [kowainik/co-log#180]
Hi!

I've adapted the function [`logException`](https://github.com/kowainik/co-log/blob/55e25bb2214b1bd8b6baf761401f87f6e9413978/co-log/src/Colog/Message.hs#L149) to also accept a severity argument, since not all exceptions are errors, in my case:

    logException severity = withFrozenCallStack
      ((withFrozenCallStack (log severity)) . T.pack . displayException)

To my surprise, I get lines like these with `<unknown loc>`:

    [93m[Warning] [0m[16-02-2020 19:54:59.451] [<unknown loc>] [ThreadId 680] /home/mb/dev/haskell/lakipea/assets/doesntExist: openBinaryFile: does not exist (No such file or directory)

I'm not sure where I took a wrong turn, since I only merged co-log's `logException` with `logError` and replaced `Error` with the `severity` argument. The original `logException` works fine for me.

Am I using `withFrozenCallStack` the wrong way?

Thanks!

---
Here are is the top of the module with the imports:

    {-# Language FlexibleContexts #-}
    module Utils.ExceptionUtil where

    import           Control.Exception              ( displayException)
    import           GHC.Stack                      ( withFrozenCallStack )
    import qualified Data.Text                     as T

    import           Colog                          ( log )
    import           Prelude                 hiding ( log )

**Comment by chshersh** [comment]
Hi @mb720! Could you also add your type signature for the `logException` function? `CallStack` is provided via `HasCallStack` constraint, which is an implicit constraint. So it's not inferred automatically if you don't write it explicitly. In `co-log` functions `HasCallStack` is provided as a part of the `WithLog` constraint.

Also, I think that one `withFrozenCallStack` is redundant. It's usually should be enough to have one `withFrozenCallStack`, maybe the double application of `withFrozenCallStack` removes `CallStack` completely. This would be my first guess :slightly_smiling_face:

**Comment by mb720** [comment]
Thanks @chshersh, adding a type signature fixed the issue!


    logException
      :: forall e m env
      . (WithLog env Message m, Exception e)
      => Severity
      -> e
      -> m ()
    logException severity =
      withFrozenCallStack (log severity . T.pack . displayException)

I removed the doubled `withFrozenCallStack`, but having it once or twice doesn't change behavior, as far as I see it.

The module header grew a bit:

    {-# Language RankNTypes, FlexibleContexts #-}
    module Utils.ExceptionUtil where

    import           Control.Exception              ( Exception
                                                    , displayException
                                                    )
    import           GHC.Stack                      ( withFrozenCallStack )
    import qualified Data.Text                     as T

    import           Colog                          ( log
                                                    , Message
                                                    , WithLog
                                                    , Severity
                                                    )
    import           Prelude                 hiding ( log )

**Comment by karamellpelle** [comment]
FYI: The `HasCallStack` constraint is provided above  by  `type WithLog env msg m = (MonadReader env m, HasLog env msg m, HasCallStack)`.
