### ISSUE TITLE
Export showTime

### ISSUE THREAD

**Issue by maralorn** [kowainik/co-log#191]
I really like the time (or general message) formatting in co-log, but sadly in my specific context cannot use RichMessage.

Right now I have solved the problem by pasting a lot of code from `Colog.Message`. For me it would be awesome if you could add `showTime` to the export list of `Colog.Message` in the next release.

This of course might need different handling depending on #190.

**Comment by chshersh** [comment]
@maralorn Thanks for your kind words about `co-log` :blush: I don't see any problems with exporting the `showTime` function. PR is welcome!
