### ISSUE TITLE
Prevent colouring by default for richMessageAction

### ISSUE THREAD

**Issue by carlosdagos** [kowainik/co-log#198]
Hello!

Thanks for `co-log`, loving it 😄 

We're using `richMessageAction`. I was wondering if there was a way to prevent colouring from happening. The issue is that in our terminals the logs look beautiful, but in prod we consume logs using Kibana, where the colours create a bit of a mess:

```
�[92m[Debug]   �[0m[09-07-2020 06:55:37.171] ...
```

**Comment by chshersh** [comment]
@carlosdagos Thanks for sharing your feedback and use case! This is indeed a useful feature. We were previously thinking about way to disable colouring, and an issue about this feature already exist: #183. So I'm closing this one as a duplicate.

**Comment by carlosdagos** [comment]
Cheers @chshersh
