### ISSUE TITLE
Add logger rotation action

### ISSUE THREAD

**Issue by ChShersh** [kowainik/co-log#20]

**Comment by ChShersh** [comment]
Sketch is in `master` under comment:

https://github.com/kowainik/co-log/blob/9f1f8151ae889364a6b0a87b8e4082ce90a5c9a9/co-log/src/Colog/Actions.hs#L98-L133

I will return to this implementation later.

**Comment by sphaso** [comment]
If that's OK @lucazulian and I would like to take a shot at this. We will likely work on it throughout this week.

**Comment by ChShersh** [comment]
@sphaso Sure, go for it!
