### ISSUE TITLE
Log Message/RichMessage to file

### ISSUE THREAD

**Issue by 4eUeP** [kowainik/co-log#208]
Since there is no action that write `RichMessage` to a file, I have implemented two functions `withLogMessageFile` and `withLogRichMessageFile`.

( I'll open a PR if it's something you'd accept :-) )

**Comment by chshersh** [comment]
Hi @4eUeP! You don't need to write `RichMessage` directly to file. `co-log` provides actions to write primitives (`Text`, `ByteString`) directory to file:

* http://hackage.haskell.org/package/co-log-0.4.0.1/docs/Colog-Actions.html#v:withLogByteStringFile

You are supposed to use the `Contravariant` nature of logging to format messages to strings. You can find some examples in the `co-log` playground:

https://github.com/kowainik/co-log/blob/45d5dd6c33f722628a0f9c10e4297f5e11ede20f/co-log/tutorials/Main.hs#L171-L194

We have plans to write even more docs and helpful tutorials, so all examples will be explained separately:

* https://github.com/kowainik/co-log/issues/84

But for now, you can check the playground and construct the desired action manually. Also, `RichMessage` is somewhat internal type, and is not supposed to be logged directly by passing values of the `RichMessage` type.

**Comment by 4eUeP** [comment]
@chshersh Thank you for your explanation! However, if the library provide a function like `withLogMessageFile`(which is something of composing `fmtMessage` and `logTextFlushHandle`), I think it will be helpful. ( Anyway, it's not necessary :smiley: )
