### ISSUE TITLE
Allow polysemy-1.4.0.0

### ISSUE THREAD

**Issue by vrom911** [kowainik/co-log#210]
https://github.com/commercialhaskell/stackage/issues/5718

**Comment by teto** [comment]
even better, could we allow 1.5 ? This blocks me from using polysemy-log ttps://github.com/tek/polysemy-log/issues/3#issuecomment-846536090 cheers and thanks for all you do for the haskell community in general.

**Comment by tek** [comment]
I already PR'd this when 1.5 was released https://github.com/kowainik/co-log/pull/219

Just have to publish to hackage

**Comment by teto** [comment]
ha ok I will override the version in the cabal.project then thanks !
