### ISSUE TITLE
Question about working with Scotty

### ISSUE THREAD

**Issue by cideM** [kowainik/co-log#215]
I don't usually create issues to ask questions, so apologies. But I asked on [StackOverflow](https://stackoverflow.com/questions/65599741/how-to-make-co-logs-withlog-work-with-scotty), [Discourse](https://discourse.haskell.org/t/help-with-logging-in-scotty-handlers/1768) and [Reddit](https://www.reddit.com/r/haskell/comments/krke1o/how_to_create_colog_instance_for_scotty/) and so far my issue wasn't resolved.

In short: I don’t know how to create an instance for co-log so I can use `withLog` in a handler in the same way I’m doing it for `katip`

I created a [repository](https://github.com/cideM/co_log_issue) where you can see the issue. I would have preferred this as a single file with a Nix shebang line but at the time of writing `co-log` was broken in Nixpkgs. I have since fixed this and will check if I can now just provide a single file.

In the meantime though… any ideas? This problem means I can’t use `co-log` here at all, since without being able to modify the logger for a given scope I miss out on the `co-log` equivalent of namespaces and contexts.

The [StackOverflow](https://stackoverflow.com/questions/65599741/how-to-make-co-logs-withlog-work-with-scotty) post includes some more details as to what I tried:

- Automatically derive the instance. Fails with Template Haskell bug apparently fixed in GHC 9
- I don't think this can even be derived since I also tried to take the derived instances and just enter them manually

What I'd love to get help with is creating

```
Could not deduce (HasLog (AppEnv App) Message (Scotty.ActionT TL.Text m))
```

**Comment by chshersh** [comment]
Hi @cideM! Sorry, We are a bit busy right now, but I'll look into the issue this week and get back to you.

**Comment by chshersh** [comment]
Hi @cideM, I've opened a PR to your repository with fixes:

* https://github.com/cideM/co_log_issue/pull/1

The code compiles and runs successfully. When I open `localhost:3123` in my browser or ping it with `curl`, I can see the correct response, and I also see that the message `foo` is logged correctly.

![Screenshot from 2021-01-24 14-15-53](https://user-images.githubusercontent.com/4276606/105633110-adb96300-5e4e-11eb-9d8f-15e5f7403a3d.png)

**Comment by cideM** [comment]
Thanks for getting back to this, I really appreciate it! This is quite the simple and straightforward change. It does bake the `Scotty` part into my logging environment. I'm not sure if this will be a problem at some point. Let's say I have a function that is used from within a route handler, but the function itself doesn't do anything Scotty specific. I guess if I want to do logging in that function I might have to do some lifting to still have the `Scotty` logging environment? I'll try to come up with an example of that.
