### ISSUE TITLE
Release for Stackage 18 series allowing ansi-terminal-0.11

### ISSUE THREAD

**Issue by ejconlon** [kowainik/co-log#222]
Hi all, can we get a new release on Hackage that includes the April change to allow `ansi-terminal >= 0.11`? (I actually think a package revision will suffice - the PR was only a bounds change.) Then this will be usable with Stackage lts-18.2. Thanks!

For reference:
https://github.com/kowainik/co-log/issues/200
https://github.com/commercialhaskell/stackage/issues/5592

**Comment by chshersh** [comment]
@ejconlon We don't support Stackage anymore as per https://github.com/commercialhaskell/stackage/pull/5965

We will release the new version to Hackage when we have the capacity to do this. Meanwhile, you can depend on the GitHub version of `co-log` using the `stack` build tool.
