### ISSUE TITLE
Use CPP to have Contravariant instance in `co-log-core` for GHC 8.6.1

### ISSUE THREAD

**Issue by ChShersh** [kowainik/co-log#40]
It's possible to use `-XCPP` extension to make `Contravariant` instance available for GHC >= 8.6.1 directly from `co-log-core` package. For this we also need to have `Contravariant` instance in `co-log` only for GHC < 8.6.1

**Comment by qnikst** [comment]
done in https://github.com/kowainik/co-log/pull/44

**Comment by ChShersh** [comment]
Merged
