### ISSUE TITLE
Performance benchmarks 

### ISSUE THREAD

**Issue by o1lo01ol1o** [kowainik/co-log#41]
Hi, this is a cool looking library.  Can I persuade you to do some performance benchmarks vs other logging libraries?  

Knowing if and where the machinery causes too much runtime overhead would lessen the barrier to adoption.

**Comment by ChShersh** [comment]
@o1lo01ol1o That would be great to do! Do you have an idea of possible benchmarks? What exactly would you like to see? How many lines `co-log` can write to the console output or to files?

**Comment by qnikst** [comment]
Partially addressed in #64 . I have not done comparison with other libraries yet.
There are 2 reasons:
1. I'm not sure I understand all features of the `co-log` library so maybe I'll not use or misuse some parts of the features.
2. I'm not sure about the minimal viable benchmark that will show how the library behaves compared to the other well-known libraries.

When running a benchmark against the other libraries it would be nice to keep feature-set in mind, e.g. if time is precise or not, can data be reordered and how, are logs structured and what tags can we add.. Though at some point such a comparison has to be made.

**Comment by ChShersh** [comment]
@o1lo01ol1o #64 (contributed by @qnikst) is merged to master now. Please, see, whether the results (described in the PR body) are what you are looking for.

**Comment by ChShersh** [comment]
@o1lo01ol1o @qnikst I think that this issue can be marked as resolved. I've created couple followup issues:

* #76 
* #77
