### ISSUE TITLE
Add `liftLogIO` to `Colog.Core.IO` module:

### ISSUE THREAD

**Issue by ChShersh** [kowainik/co-log#48]
This function:

```haskell
liftLogIO :: MonadIO m => LogAction IO msg -> LogAction m msg
```

This might be useful.

**Comment by cronokirby** [comment]
Maybe this should go in `Colog.Monad` instead?

- It avoids adding a new module
- It avoids adding a dependency (for `MonadIO`) in `co-log-core`
- It would go right next to the existing `liftLogAction`
