### ISSUE TITLE
Add fancy operator to pass `msg` to `LogAction m msg`

### ISSUE THREAD

**Issue by ChShersh** [kowainik/co-log#49]
Currently, in order to pass `msg` to `LogAction m msg` you need to write the following code:

```haskell
unLogAction logAction msg
```

This might not be convenient. It would be much cooler to have some fancy operator to pass logs to actions, like this one:

```haskell
logAction <| msg
```

Maybe `<|` is not the best choice, since it's already a popular operator name. So I'm open to proposal for better names.

**Comment by cronokirby** [comment]
How about `<-|` and `|->` as a symmetric pair?
I think having a symmetric pair of thing to be able to do
```haskell
logAction <-| msg
msg |-> logAction
```

**Comment by cronokirby** [comment]
Another option would be `<--` which looks more like "sending a message" to me:
```haskell
logAction <-- msg
msg --> logAction
```

**Comment by ChShersh** [comment]
Somehow I find `|->` akward to type and to use. I would prefer to have two-character operators. The problem with `-->` is because it looks like comment, so some parsers may fail with it.

I'm thinking more about some similiraties with shell. Maybe we can introduce `&>` and `<&` operators? Like:

```haskell
logAction <& msg
msg &> logAction
```

Surprisingly, this name is not that popular on Hackage 🤔 Which means that we can take it.

**Comment by cronokirby** [comment]
Yeah on the standard us keyboard `|->` is kind of all over the place, I like `&>`
