### ISSUE TITLE
Add `logShowStdout` to Colog.Core.IO

### ISSUE THREAD

**Issue by cronokirby** [kowainik/co-log#63]
This came up in #61 while resolving #58:

In the documentation examples it was often needed to log a value implementing `Show`, e.g. Int, (), etc.
I think this would a useful function to add to Colog.Core.IO.
`logShowStdout` is just a first idea of a name; it matches `logStringStdout`, but maybe we want `logPrint`
or something else instead.

**Comment by ChShersh** [comment]
@cronokirby I'm actually okay with `logPrint` because by default `print` outputs to `stdout` so `logPrint` is short and self-explanatory name. If desired, we can add `logPrintStderr` though it kinda against convention... I propose to gather more feedback under this issue before implementing.
