### ISSUE TITLE
Bump up to `relude-0.4.0`

### ISSUE THREAD

**Issue by ChShersh** [kowainik/co-log#68]
Checklist:

1. Update bounds in `.cabal` file.
2. Update in `stack.yaml`
3. Update HLint rules.
4. Add check for HLint rules to the Travis CI and fix all HLint warnings and hints.

**Comment by cronokirby** [comment]
So I've started working on this, and have found a few places to apply hlint suggestions, however I'm not too sure how to deal with this failure:
```
Found:
        MessageField
            :: forall fieldName m .
  >            { unMesssageField :: m (FieldType fieldName) }
            -> MessageField m fieldName


1 hint
```

This is a perfectly compiling thing, but hlint can't parse it because of the advanced extensions used. How should we go about getting hlint to ignore this in the travis build?

**Comment by vrom911** [comment]
@cronokirby are you using `relude` specific `hlint` file? It has all necessary extensions included, so you shouldn't have any issues. 

You can specify it in `.hlint.yaml` like this:

```yaml
- arguments:
  - -XConstraintKinds
  - -XDeriveGeneric
  - -XGeneralizedNewtypeDeriving
  - -XLambdaCase
  - -XOverloadedStrings
  - -XRecordWildCards
  - -XScopedTypeVariables
  - -XStandaloneDeriving
  - -XTupleSections
  - -XTypeApplications
  - -XViewPatterns
```

**Comment by cronokirby** [comment]
Yep, I'm using https://raw.githubusercontent.com/kowainik/relude/988bbdd3a09df1159917012933780523644880e5/.hlint.yaml, from the latest commit on relude, but despite the extensions in the hlint file, the parse error persists :thinking:

**Comment by ChShersh** [comment]
@vrom911 @cronokirby Okay, looks like `haskell-src-exts` library can't parse GADTs with records at the moment:

* https://github.com/haskell-suite/haskell-src-exts/issues/324

I think the workaround for now is to remove this record from `newtype` definition and implement as a separate function with proper order of `forall` variables.

**Comment by ChShersh** [comment]
Closing in favor of #74
