### ISSUE TITLE
Custom  `Severity` for `Message`

### ISSUE THREAD

**Issue by ShrykeWindgrace** [kowainik/co-log#97]
Different logging frameworks implement different range of message severity, e.g. 0-7 for `syslog` and `log4j` (up to a choice of names), 1-7 in `cisco`, `slf4j` has a mechanism for custom severity levels, and so on.

From the point of view of formatting/filtering all these severity level implementations look the same.

I'd say it could be useful to have a typeclass `MSeverity` with required instances/formatting functions with an `instance MSeverity Severity`, and then parameterize `Message` by an instance of `MSeverity`.

What do you think?

**Comment by ChShersh** [comment]
@ShrykeWindgrace Your suggestion makes sense to me. I'm all hands for making `co-log` more flexible so people can implement other logging backends on top of it easier. The `Message` data type is not that flexible at the moment, which might bring some inconvenience for writing custom backends (especially in the context when all functions are fixed to this particular data type), I understand that. There are already some thoughts about making `Message` type more flexible: see issue #28.

`MSeverity` typeclass can solve this particular problem for allowing different types of `Severity`, which is already quite useful. But at the same time this looks like a partial ad-hoc solution for bigger problem: making `Message` type completely configurable.

My wishlist for `Message`:

1. Ability to specify `CallStack`
2. Ability to specify `Severity`: the type of severity, presence/absence of severity.
3. Any arbitrary payload for the `Message`: this can be `Text` like now, or `Map Tag Data` if somebody wants.
4. Specify `Message` formatting.
5. Ideally make all fields equal and uniform.
6. Implement `Monoid` instance for `Message` (this is important for comonadic part of the library).

So before going with `MSeverity` solution, I propose to think about more general solution that can solve all problems at once.

**Comment by ShrykeWindgrace** [comment]
I see your point. However, to me your plan seems to be too "open-world", trying to cover all possible use-cases.

Implementing a reasonable monoid instance even for the current `Message` alone seems like a decision to make, I can easily imagine ~3-4 viable approaches, and I guess you can imagine many more contradicting usecases as well.

As per your points:
1. sure!
1. just a field `MSeverity a => Maybe a`?
1. Can be done with `cmap`, can't it? It definitely seems interesting, though
1. Per Message? Or Global formatter?
1. I don't quite see what you mean by that =)

Cheers!

**Comment by ChShersh** [comment]
@ShrykeWindgrace I think I can come up with several typeclasses to cover basic cases. I have an idea now how to do this. Will try to come up with the implementation soon.

**Comment by chshersh** [comment]
@ShrykeWindgrace I've created issue #103 that should help in making `co-log` more flexible. I don't want to introduce new typeclasses when I can't come up with reasonable laws for them. So something like this looks awkward to me:

```haskell
class MSeverity a sev where
    getSeverity :: a -> Maybe sev
    fmtSeverity :: sev -> Text
```

With new approach you can just create your own formatting function for your own severity and use it instead of default one. I suppose this should cover your use case 🙂

**Comment by ShrykeWindgrace** [comment]
Great, thanks!
